version: '3.2'
services:
  wormhole-demo:
    build: https://github.com/EdwardJXLi/WormholeExampleServer.git#main
    container_name: wormhole-demo
    restart: unless-stopped
    ports:
      - 8000:8000
    logging:
      driver: "json-file"
      options:
          max-file: 3
          max-size: 10m
